In [ ]:
# importing libraries
import pandas as pd
from sklearn.ensemble import VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

# loading iris dataset
data = pd.read_csv("heart_failure_clinical_records_dataset.csv")
data.head()

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time,DEATH_EVENT
0,75.0,0,582,0,20,1,265000.00,1.9,130,1,0,4,1
1,55.0,0,7861,0,38,0,263358.03,1.1,136,1,0,6,1
2,65.0,0,146,0,20,0,162000.00,1.3,129,1,1,7,1
3,50.0,1,111,0,20,0,210000.00,1.9,137,1,0,7,1
4,65.0,1,160,1,20,0,327000.00,2.7,116,0,0,8,1

In [ ]:
data = data.sample(frac=1) 
labels = data['DEATH_EVENT'] 
features = data.drop('DEATH_EVENT', axis=1) 
"""X = iris.data[:, :4] Y = iris.target
train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.20, random_state = 42)"""

#train_features, test_features, train_labels, test_labels
X_train, X_test, y_train, y_test = train_test_split( features, labels, test_size=0.30)

#group / ensemble of models
estimator = [] 
estimator.append(('LR', LogisticRegression(max_iter = 1500))) 
estimator.append(('SVC', SVC(kernel='linear',probability= True))) 
estimator.append(('DTC', DecisionTreeClassifier(criterion='entropy')))
estimator.append(('RF', RandomForestClassifier()))
estimator.append(('ETC', ExtraTreesClassifier(max_depth=10)))
#Voting Classifier with hard voting
vot_hard = VotingClassifier(estimators = estimator, voting ='hard') 
vot_hard.fit(X_train, y_train) 
y_pred = vot_hard.predict(X_test)

#using accuracy_score metric to predict accuracy
score = accuracy_score(y_test, y_pred) 
print("Hard voting accuracy is",score) 
print("Hard Voting Score % d" % score)

#Voting Classifier with soft voting
vot_soft = VotingClassifier(estimators = estimator, voting ='soft')
vot_soft.fit(X_train, y_train)
y_pred = vot_soft.predict(X_test)
  
# using accuracy_score
score = accuracy_score(y_test, y_pred)
print("Soft voting accuracy is",score)
print("Soft Voting Score % d" % score)

Hard voting accuracy is 0.9111111111111111
Hard Voting Score  0
Soft voting accuracy is 0.9
Soft Voting Score  0